name: GitHub Actions Update Json On Monday
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  schedule:
    - cron: "0 4 * * 1"
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Run Script to update F1 data
        run: bash getF1Data.sh force_update

      - name: Check for modified files
        id: git-check
        run: echo "modified=$(if [ -n "$(git status --porcelain)" ]; then echo "true"; else echo "false"; fi)" >> "$GITHUB_OUTPUT"

      - name: Commit files if there are some changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --local user.name  ${{ github.actor }}
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Updating automatic repository"
      - name: Push changes # push the output folder to your repo
        if: steps.git-check.outputs.modified == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
