name: GitHub Actions Update Json On Monday
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  schedule:
    - cron: "0 4 * * 1"
  workflow_dispatch:
jobs:
  Force-Update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Run Script to update F1 data
        run: bash getF1Data.sh force_update

      - name: Check for modified files
        id: git-check
        run: |
          deleted_files=$(git status --porcelain | grep "^ D" | wc -l)
          modified_files=$(git status --porcelain | grep "^ M" | wc -l)
          added_files=$(git status --porcelain | grep "^A" | wc -l)
          untracked_files=$(git status --porcelain | grep "^??" | wc -l)

          echo "Deleted files count: $deleted_files";
          echo "Modified files count: $modified_files"
          echo "Added files count: $added_files"
          echo "Untracked files count: $untracked_files"
        
          if [ "$deleted_files" -gt 0 ]; then
            echo "modified=false" >> "$GITHUB_OUTPUT"
          elif [ "$modified_files" -gt 0 ] || [ "$added_files" -gt 0 ] || [ "$untracked_files" -gt 0 ] ; then
            echo "modified=true" >> "$GITHUB_OUTPUT"
          else
            echo "modified=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Commit files if there are some changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --local user.name  ${{ github.actor }}
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Updating automatic repository"
      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
